### ISSUE TITLE
amazing job. 

### ISSUE THREAD

**Issue by johndpope** [slavaim/MacOSX-Kernel-Filter#1]
It looks like El Capitan kernel framework  has some trouble finding headers that should be there. 
# include <IOKit/usb/IOUSBHubDevice.h>

Did you get this working? 
I'm going to see how far I can get building it with the older 10.10 SDK framework.

![screen shot 2015-11-29 at 6 31 18 pm](https://cloud.githubusercontent.com/assets/289994/11455887/7c4b8a9a-96c7-11e5-9d58-02ca63812052.png)

**Comment by johndpope** [comment]
Hi Slava,

fyi,
 the user settings in your project file didn't include any definitions. I had to invent these. 
Can you see any mistake here?

![screen shot 2015-11-29 at 9 35 24 pm](https://cloud.githubusercontent.com/assets/289994/11456571/23ec1f30-96e1-11e5-931a-59e507ddbe30.png)

I dug up a 10.10 sdk and built kext -> but on el capitan it's failing to validate.

Found this which details El Capitan rebuilt  the USB framework. 
'The USB stack is completely redesigned to increase stability and performance compared to Mac OS 10.10. Applications and third-party drivers for vendor-specific USB devices built with 10.10 SDK require no modification.'
https://developer.apple.com/library/prerelease/mac/releasenotes/Darwin/RN_USB/Articles/10_11Changes.html#//apple_ref/doc/uid/TP40007739-CH3-SW1

More details here ->
https://forums.developer.apple.com/message/48612#48612

For some reason - even though it compiles fine with 10.10 sdk - I still get this error.
Google didn't help. I wonder if my definitions have lead the driver astray.

sudo kextlibs -xml -undef DLDriver.kext/
         <key>OSBundleLibraries</key>
        <dict>
                <key>com.apple.iokit.IOSCSIArchitectureModelFamily</key>
                <string>3.7.7</string>
                <key>com.apple.kpi.bsd</key>
                <string>15.2</string>
                <key>com.apple.kpi.iokit</key>
                <string>15.2</string>
                <key>com.apple.kpi.libkern</key>
                <string>15.2</string>
                <key>com.apple.kpi.mach</key>
                <string>15.2</string>
                </dict>

For x86_64:
    13 symbols not found in any library kext:
    _pmap_find_phys
    _mac_kalloc
    _proc_iterate
    _mac_kfree
    _mac_policy_register
    _kernel_pmap
    _mac_policy_unregister
    _vfs_context_current
    _mac_proc_set_enforce
    _proc_lock
    _kauth_cred_issuser
    __ZN21DldIOServiceTreeEntry25CollectParentsInformationEv
    _proc_unlock

getting a similar thing on Yosemite > 
kextlibs DLDriver.kext/ -undef
For all architectures:
    com.apple.iokit.IOSCSIArchitectureModelFamily = 3.7
    com.apple.kpi.bsd = 14.0
    com.apple.kpi.iokit = 14.0
    com.apple.kpi.libkern = 14.0
    com.apple.kpi.mach = 14.0

For x86_64:
    13 symbols not found in any library kext:
    _pmap_find_phys
    _mac_kalloc
    _proc_iterate
    _mac_kfree
    _mac_policy_register
    _kernel_pmap
    _mac_policy_unregister
    _vfs_context_current
    _mac_proc_set_enforce
    _proc_lock
    _kauth_cred_issuser
    __ZN21DldIOServiceTreeEntry25CollectParentsInformationEv
    _proc_unlock

kextfind -dsym _pmap_find_phys
/System/Library/Extensions/System.kext/PlugIns/Unsupported.kext
/ is this deprecated since Mavericks - I wonder.

I'm wondering if - com.apple.kpi.unsupported dependencies means this project is no longer usable.
https://developer.apple.com/library/mac/qa/qa1575/_index.html

The com.apple.kpi.unsupported KPI is a compatibility measure intended for use by a limited number of Apple KEXTs. Your KEXT should not depend on this unsupported functionality.

**Comment by johndpope** [comment]
fyi - > not sure if you are aware of this app -  https://github.com/johndpope/iojones

**Comment by slavaim** [comment]
Hi,

I will do some changes to the project as it happens I didn't add an important part to the github repository that is responsible for resolving kernel symbols.

**Comment by slavaim** [comment]
I also believe that kextlibs reports as missing symbols from com.apple.kpi.unsupported , just a trick to discourage developers from using these APIs. Nevertheless a kernel extension using that API is still loadable.

**Comment by slavaim** [comment]
I changed the project. A new driver was added - DlDriverPrivate.kext. This is a proxy driver like com.apple.kpi.bsd that doesn't contain any code. Its goal is to export symbols from the Mac OS X kernel in the same way com.apple.kpi.bsd does. To load DlDriver you need to add the DlDriverPrivate as a dependence like "sudo kextload DlDriver.kext -d DlDriverPrivate.kext"

**Comment by slavaim** [comment]
I build the project with 10.9 SDK , this doesn't prevent it from loading on 10.10 or 10.11 , but some modification required for 10.11 because of a changed USB stack ( as you mentioned ).

**Comment by slavaim** [comment]
> fyi - > not sure if you are aware of this app - https://github.com/johndpope/iojones

it is interesting as unstable Apple's IORegistryExplorer drives me mad by constantly crashing when my driver creates its own IOKit tree

**Comment by johndpope** [comment]
Thank you Slava.
