### ISSUE TITLE
Clarification on inspecting traffic

### ISSUE THREAD

**Issue by johndpope** [slavaim/MacOSX-Kernel-Filter#2]
Hello Slava,

I appreciate any insight you can provide here - ( I am in the deep end)
I have the kext running in conjunction with iojones and I can see the device tree it discovers. ![Uploading Screen Shot 2016-01-18 at 7.20.07 PM.png…]()

If I plug in a thunderbolt device / ( not a hdd) - which methods would be appropriate to sniff the iokit 'traffic'?  From looking through some of classes - I can see there's some tcp methods related to intercepting ip traffic (FltDataIn and the FltDataOut ) 

After digging around for  a few hours  inside - the IOKitDriver.cpp it appears that you're specifically hooking into / targeting / intercepting a usb device  IOUSBMassStorageClass::HookObject 
Or are all objects in the tree already 'hooked'

```
  if( 0x0 == strcmp( (char*)ClassName->getCStringNoCopy() ,"IOUSBMassStorageClass" ) ) {
            IOUSBMassStorageClass*   USBMassStorageClassInstancePtr;
            __asm__ volatile( "int $0x3" ); // presumably this is to allow you to hook in to a remote debug session
            USBMassStorageClassInstancePtr = (IOUSBMassStorageClass*)service;
            IOUSBMassStorageClassDldHook::HookObject( USBMassStorageClassInstancePtr );

        }
```

I (think I ) want to hook into a subclass of ioservices.

```
        //IOClass, String,
        if( 0x0 == strcmp( (char*)ClassName->getCStringNoCopy() ,"com_company_driver" ) ) {

            DldHookerCommonClass*   ClassInstancePtr = (DldHookerCommonClass*)service;

            DldHookerCommonClass::HookObject( ClassInstancePtr, DldHookTypeUnknown ); // couldn't 
        }
```

the DldHookerCommonClass and DldHookerCommonClass2 appear to inherit different classes and don't really correlate to your example. Any ideas?

I assume once you have issued - IOUSBMassStorageClassDldHook:hookobject - then you can hook into the traffic here? That's what's I'm trying to do. 

![Uploading Screen Shot 2016-01-18 at 7.20.07 PM.png…]()
What would be a way to show the iokit calls?

![Uploading Screen Shot 2016-01-18 at 9.22.51 PM.png…]()

I'm dreaming of an app (perhaps a fork of iojones) where I can tap into a targeted node and inspect traffic.

**Comment by slavaim** [comment]
Hi,

There is a problem with markdown as I do not see any images.

In 2010 I redesigned the hooker, the old hooker DldHookerCommonClass was used in the code based on C macro-definitions - that was ugly, unmanageable and impossible to debug.

The new DldHookerCommonClass2 was C++ template based. I preserved the old code for reference( look for #if 0 macro that switches off some files). I decided to intercept all mass storage traffic at the file system level as a better solution for my goals, so I hook IOUSBMassStorageClass only to support upper level processing at the file system level( i.e. hooked its IOService interface ) and hooked IOUSBMassStorageClass::SendSCSICommand as this can't be intercepted at the file system level( used for CD/DVD burning when there is no mounted file system), the actual hooking for IOUSBMassStorageClass is registered here

``` C++
 this->DldAddHookingClassInstance< IOUSBMassStorageClassDldHook2<DldInheritanceDepth_0>, IOUSBMassStorageClass >( DldHookTypeObject );
```

There are some issues with your design. Your design is easily fit for Windows where most drivers have a dispatch table that is used to call them, so it is possible to create a hooker that fits all drivers. In the Mac OS X case each driver has its own C++ interface class for communication. So if you want to watch "traffic" you need to know what to hook for a particular class.  For example to intercept write requests( i.e. traffic ) to optical drives I need to hook IOUSBMassStorageClass::SendSCSICommand , so you can see it in the code

``` C++
template<DldInheritanceDepth Depth>
class IOUSBMassStorageClassDldHook2 : public DldHookerBaseInterface
{
 ...........    
    //
    // The SendSCSICommand function will take a SCSITask Object and transport
    // it across the physical wire(s) to the device
    //
    virtual bool SendSCSICommand_hook( SCSITaskIdentifier       request, 
                                       SCSIServiceResponse *    serviceResponse,
                                       SCSITaskStatus      *    taskStatus );

};
```

and then register this function as a hook function

``` C++
template<DldInheritanceDepth Depth>
bool
IOUSBMassStorageClassDldHook2<Depth>::init()
{
 ..........        
        //
        // add new hooking functions specific for the class
        //
        this->mHookerCommon2->fAddHookingFunctionExternal(
                                                          kDld_SendSCSICommand_hook,
                                                          DldConvertFunctionToVtableIndex( (void (OSMetaClassBase::*)(void)) &PureVirtualClass::SendSCSICommand ),
                                                        DldHookerCommonClass2<IOUSBMassStorageClassDldHook2<Depth>,IOUSBMassStorageClass>::_ptmf2ptf( this, (void (DldHookerBaseInterface::*)(void)) &IOUSBMassStorageClassDldHook2<Depth>::SendSCSICommand_hook ) );

..............
}
```

You need to do this for all classes and functions you want to hook. There is a caveat here - some interfaces return object that a caller use for subsequent communications and this object is not discoverable via IOService or any other objects tree, so you need to hook the returned object which is not always possible as your driver loads after the object was returned. But the good point here is that you can see "traffic" at some point above or below in the IOService tree.

I would be happy to help with any issues. I am thinking of writing a design manual for a hooker and other parts of the project but I am short on time.

**Comment by slavaim** [comment]
This kernel extension is capable to filter any IOKit object in the system that has an interface declared with virtual functions , which is nearly all IOKit interfaces, or via VFS(Virtual File System ). You just need to add the code to declare the interface as being hooked. The current code was designed to filter user initiated I/O so it uses a hook for IOUserClient and VFS(Virtual File System ) hooks. Also all IOKit objects' IOService interface is hooked to provide information about object type to IOUserClient and VFS hooks. The kernel extension builds its own IOKit tree of hooked objects ( which is nearly identical to IOService tree ) which you can see with IO Jones or IORegistryExplorer by DldDeviceTreePlane name. This tree can be used to export data or provide data to the kernel extension via SetProperty function of an object.

**Comment by johndpope** [comment]
Thanks for your patience and pointing me in right direction. The usbmassstorage header file - I can see how you've subclassed this. 

I searched around for a IOPCIDevice subclass and  found this class on another repo 
https://github.com/RehabMan/OS-X-Fake-PCI-ID/blob/17774b2696a4ba48e790d5966e6b340725021ca7/FakePCIID/PCIDeviceStub.cpp

class PCIDeviceStub : public IOPCIDevice
It's overriding methods related to reading / writing to pci / thunderbolt.
The way this is instantiated / and life cycle - it is invoked by matching device ids - and then inserting the FakePCCIID class in plist 

![screen shot 2016-01-19 at 12 48 08 pm](https://cloud.githubusercontent.com/assets/289994/12407383/efb52cc4-beaa-11e5-851e-4147ff8d07ad.png)

If I proceed down this path - I can't allow the device to function properly - as I don't have the headers / sdk for the proprietary class that I need instantiate. 

From your code - it's more flexible in that it the device is already on and  instantiated and you're hooking into it. (you don't need to boot up)

so when you iterate through the IOServices in DumpTree( void )  method 
- I thought I could hook in here - 
  
  ```
      kprintf(  "com_devicelock_driver_DeviceLockIOKitDriver->DumpTree: found name %s \n", (char*)ClassName->getCStringNoCopy() ) ;
  
      //IOClass, String,
      if( 0x0 == strcmp( (char*)ClassName->getCStringNoCopy() ,"com_company_driver_PCI" ) ) {
  
          IOPCIDevice*   provider = (IOPCIDevice*)service;
          FakePCIID  *fake = new FakePCIID();
          fake->init(dict);
          fake->hookProvider(provider);
      }
  ```

does that look feasible to you?
Actually - looking at these classes - they're calling super methods - so I don't think this going to work. 
I need to flesh out a new pci hook class similar to your usb class and the PCIDeviceStub class.

**Comment by slavaim** [comment]
My code will work if functions are declared as virtual, i.e. present in the C++ object's vtable. All public IOKit interface functions declared as virtual, most of the Apple proprietary interfaces are also virtual but there is no headers. 

I browsed FakePCIID code. The code is not as flexible as mine, it requires a kext to be loaded on boot which is not practical as any bug renders the system unusable. It is too invasive , it is not practical to replace or attach to all objects in the system if your intention is to intercept "traffic". It attaches an object so requires a full knowledge about all interfaces in the inheritance chain , while my driver allows to hook a known interface in the middle if a final class in the inheritance is not known. FakePCIID replaces the whole virtual table , so the access to all class declarations is essential. My driver in additional to this type supports another type of hooking when vtable is patched - look at DldHookType definition. This type allows to set hooks when a size for a vtable is not known because of a missing header(s) for a final class in inheritance chain.

P.S. My hooker's code is a way bigger than FakePCIID, but this is a result of making it as flexible as possible to allow hooking all objects in the system.
