### ISSUE TITLE
How can I unload driver manually?

### ISSUE THREAD

**Issue by ujinyang** [slavaim/MacOSX-Kernel-Filter#3]
How can I unload driver manually?

I try to unload driver.
> kextunload DLDriver.kext/
And click enter key.
Then, just blue-screen appeared on OSX 10.6.8.

What is correct way! Plz, guide me.

**Comment by slavaim** [comment]
My advise is to never unload this kext as it was not designed to support unloading. It is too difficult to unhook without running into race conditions with other parts of the system. I believe you compiled a debug version which has a code for unload but it has not been tested and used for years. To prevent the kext from unloading just increment the reference count for IOKit kext object in the start routine

bool
com_devicelock_driver_DeviceLockIOKitDriver::start(
    __in IOService *provider
    )
{
......
__exit:
    assert( true == bRet );
    if( bRet ) this->retain();
    return bRet;
}
